name: Build domains_all and ipsum

on:
  workflow_dispatch: # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 */3 * *' # Runs every 3rd day at midnight UTC

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests idna geoip2

    - name: Prepare directories for build
      run: |
        mkdir -p $GITHUB_WORKSPACE/sum/input
        mkdir -p $GITHUB_WORKSPACE/sum/output

    - name: Run OONI Parser (ooni_domains.lst)
      run: python "src/step 5 ooni list/ooni_list.py"

    - name: Run Domain Sum Up script (domains_all.lst) ##Community.lst goes from root folder
      run: python "src/step 5 ooni list/domain_sum.py"

    - name: Run OONI Resolver script (ooni_ips.lst)
      run: python "src/step 5 ooni list/resolver_ooni.py"

    - name: Run Community Resolver script (ip_community.lst)
      run: python "src/step 5 ooni list/resolver_community.py"

    - name: Run IP Sum (Temp) script (ips_all.lst) ##discord_ips.lst goes from root folder
      run: python "src/step 5 ooni list/ip_4files_sum.py"

    - name: Run IP Sum + ASN (Final) script (ipsum.lst)
      run: python "src/step 6 temp - summarization and ASN CIDRs.py"

    - name: Verify ipsum.lst Output
      run: |
        echo "Checking for ipsum.lst in sum/output:"
        ls -la $GITHUB_WORKSPACE/sum/output/
        cat $GITHUB_WORKSPACE/sum/output/ipsum.lst || echo "ipsum.lst not found or empty"

    - name: Run Bird2 Converter script
      run: python "src/bird2_converter.py"

    - name: Convert files to LF (Unix format)
      run: |
        sudo apt-get update && sudo apt-get install -y dos2unix
        find $GITHUB_WORKSPACE -type f -name "*.lst" -exec dos2unix {} +
        
    - name: Verify Output
      run: |
        echo "Files in sum/output after build:"
        ls -la $GITHUB_WORKSPACE/sum/output

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Prepare Xray-GeoIP
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/xray-geoip
        if [ -f $GITHUB_WORKSPACE/sum/output/ipsum.lst ]; then
          cp $GITHUB_WORKSPACE/sum/output/ipsum.lst $GITHUB_WORKSPACE/src/xray-geoip/ipsum.lst
        else
          echo "Error: ipsum.lst not found!" && exit 1
        fi
        cd $GITHUB_WORKSPACE/src/xray-geoip
        go run ./ 

    - name: Prepare Xray-Geosite
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/xray-geosite/data
        if [ -f $GITHUB_WORKSPACE/sum/output/domains_all.lst ]; then
          cp $GITHUB_WORKSPACE/sum/output/domains_all.lst $GITHUB_WORKSPACE/src/xray-geosite/data/refilter
        else
          echo "Error: domains_all.lst not found!" && exit 1
        fi
        cd $GITHUB_WORKSPACE/src/xray-geosite
        go run ./ --exportlists=refilter --outputname=geosite.dat

    - name: Prepare Sing-Box Files
      run: |
        # Ensure the sing-box and refilter directories exist
        mkdir -p $GITHUB_WORKSPACE/src/sing-box/refilter

        # Check if required input files exist
        if [ -f $GITHUB_WORKSPACE/sum/output/domains_all.lst ] && [ -f $GITHUB_WORKSPACE/sum/output/ipsum.lst ]; then
          # Copy the required files to the sing-box/refilter directory
          cp $GITHUB_WORKSPACE/sum/output/domains_all.lst $GITHUB_WORKSPACE/src/sing-box/refilter/include-domain-refilter_domains.lst
          cp $GITHUB_WORKSPACE/sum/output/ipsum.lst $GITHUB_WORKSPACE/src/sing-box/refilter/include-ip-refilter_ipsum.lst

          # Prepend '*. ' to each domain in the include-domain-refilter_domains.lst file
          sed -i 's/^/*./' $GITHUB_WORKSPACE/src/sing-box/refilter/include-domain-refilter_domains.lst
        else
          # Exit with an error if the required input files are missing
          echo "Error: Required input files (domains_all.lst or ipsum.lst) are missing!" && exit 1
        fi

        # Navigate to the sing-box directory
        cd $GITHUB_WORKSPACE/src/sing-box

        # Ensure the script is executable
        chmod +x generate-geoip-geosite

        # Run the generate-geoip-geosite script
        ./generate-geoip-geosite -s sourceRefilter.json -i ./refilter -o ./refilter
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          sum/output/
          sum/input/ooni_domains.lst
          src/xray-geoip/output/dat/geoip.dat
          src/xray-geosite/geosite.dat
          src/sing-box/refilter/geoip.db
          src/sing-box/refilter/geosite.db
          src/sing-box/refilter/ruleset-domain-refilter_domains.srs
          src/sing-box/refilter/ruleset-domain-refilter_domains.json
          src/sing-box/refilter/ruleset-ip-refilter_ipsum.srs
          src/sing-box/refilter/ruleset-ip-refilter_ipsum.json
